### Get all products
GET http://localhost:8080/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwicm9sZSI6IkNMSUVOVCIsImlhdCI6MTc3NTU3NTM1MCwiZXhwIjoxNzc1NTc4OTUwfQ.PLW8NUVZ9caruMVgonQq1oE3I4bkLHdGe3mvDqbnQTU

### Create product
POST http://localhost:8080/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwicm9sZSI6IkNMSUVOVCIsImlhdCI6MTc3NTU3NTAzMCwiZXhwIjoxNzc1NTc4NjMwfQ.aTp5ZWAjwpiCNWXz39DYBoR-4cABx7os30blCDYj8_o

{
  "name": "Test Skates3",
  "category": "SKATES",
  "type": "FREESKATE",
  "price": 500,
  "stock": 5
}

### create cart
POST http://localhost:8080/api/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwicm9sZSI6IkNMSUVOVCIsImlhdCI6MTc3NTU3NTM1MCwiZXhwIjoxNzc1NTc4OTUwfQ.PLW8NUVZ9caruMVgonQq1oE3I4bkLHdGe3mvDqbnQTU

### Get cart
GET http://localhost:8080/api/cart/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwicm9sZSI6IkNMSUVOVCIsImlhdCI6MTc3NTU3NTM1MCwiZXhwIjoxNzc1NTc4OTUwfQ.PLW8NUVZ9caruMVgonQq1oE3I4bkLHdGe3mvDqbnQTU

### put to cart
POST http://localhost:8080/api/cart/1/add/2?quantity=1

### put 2 to cart
POST http://localhost:8080/api/cart/1/add/1?quantity=2

### register user
POST http://localhost:8080/api/auth/register?email=test@test.com&password=1234&role=ADMIN

### login user
POST http://localhost:8080/api/auth/login?email=test@test.com&password=1234