### Get all products
GET http://localhost:8080/api/products

### Create product
POST http://localhost:8080/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiJhZG1pbkB0ZXN0LmNvbSIsImlhdCI6MTc3NjAzMTUxNCwiZXhwIjoxNzc2MDM1MTE0fQ.svYcm8tbu3PMEt-PspN07FTOL94RAoEHER9u7P61f10

{
  "name": "Test Skates333",
  "category": "SKATES",
  "type": "FREESKATE",
  "price": 500,
  "stock": 5
}

### Test Create product should fail because business logic of skates not being accessory
POST http://localhost:8080/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiJhZG1pbkB0ZXN0LmNvbSIsImlhdCI6MTc3NjExNjcwMiwiZXhwIjoxNzc2MTIwMzAyfQ.aK2mAiTw6IQqDZg08nDC5tK9MGc99CXNvEr5TASjgAA

{
  "name": "Test Skates333",
  "category": "SKATES",
  "type": "CRASHPADS",
  "price": 500,
  "stock": 5
}

### Test Create product should fail because business logic of accessory not being skates
POST http://localhost:8080/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiJhZG1pbkB0ZXN0LmNvbSIsImlhdCI6MTc3NjExNjcwMiwiZXhwIjoxNzc2MTIwMzAyfQ.aK2mAiTw6IQqDZg08nDC5tK9MGc99CXNvEr5TASjgAA

{
  "name": "Test Skates333",
  "category": "ACCESSORIES",
  "type": "FREESKATE",
  "price": 500,
  "stock": 5
}


### create cart
POST http://localhost:8080/api/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwicm9sZSI6IkNMSUVOVCIsImlhdCI6MTc3NTgzMDU0NiwiZXhwIjoxNzc1ODM0MTQ2fQ._p2-udIx3E9s2Uxz2rFhPh7_3IF21D3JdIfnnglvR70

### Get cart
GET http://localhost:8080/api/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQ0xJRU5UIiwic3ViIjoidXNlckB0ZXN0LmNvbSIsImlhdCI6MTc3NjYyMTQzOSwiZXhwIjoxNzc2NjI1MDM5fQ.uf3dn0WC9zPRCK0Lt5V6y459swPCnJa1rsxl8JrSG6E

### put to cart
POST http://localhost:8080/api/cart/add
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQ0xJRU5UIiwic3ViIjoidXNlckB0ZXN0LmNvbSIsImlhdCI6MTc3NjYyMTQzOSwiZXhwIjoxNzc2NjI1MDM5fQ.uf3dn0WC9zPRCK0Lt5V6y459swPCnJa1rsxl8JrSG6E
Content-Type: application/json

{
  "productId": 2,
  "quantity": 1
}

### put 2 to cart
POST http://localhost:8080/api/cart/add/1?quantity=2

### register user
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "user52@test.com",
  "password": "123"
}

### login user
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "1234"
}