### Get all products
GET http://localhost:8080/api/products
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNzc1NTU4NDczLCJleHAiOjE3NzU1NjIwNzN9.hqC9Rhka4FLCLIICR2NrKAEssDL2w_MOnocgwvpOjfo

### Create product
POST http://localhost:8080/api/products
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNzc1NTU4NDczLCJleHAiOjE3NzU1NjIwNzN9.hqC9Rhka4FLCLIICR2NrKAEssDL2w_MOnocgwvpOjfo

{
  "name": "Test Skates3",
  "category": "SKATES",
  "type": "FREESKATE",
  "price": 500,
  "stock": 5
}

### create cart
POST http://localhost:8080/api/cart

### Get cart
GET http://localhost:8080/api/cart/1

### put to cart
POST http://localhost:8080/api/cart/1/add/2?quantity=1

### put 2 to cart
POST http://localhost:8080/api/cart/1/add/1?quantity=2

### register user
POST http://localhost:8080/api/auth/register?email=test2@test.com&password=1234&role=ADMIN

### login user
POST http://localhost:8080/api/auth/login?email=test@test.com&password=1234